### PR TITLE
Fix Observes through proxy

### LINKED ISSUE #56: Proxy blocks observe responses
Identified by @ClaesNilsson

If a GET observe request is sent through the proxy then only the first response of the request is received.

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #56

### CODE REVIEW

File: lib/middlewares.js [hunk 1]
```diff
@@ -63,6 +64,14 @@ function proxyRequest(request, next) {
   }
 }
 
+function isObserve(packet) {
+  function or(previous, current) {
+    return previous || current;
+  }
```
Comment (mcollina) [inline lib/middlewares.js]: can you move this or function externally?

Comment (dmoranj) [inline lib/middlewares.js]: Fixed in 6a69d4a
